version: "3"
services:
  react-app:
    container_name: react-app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - mern-app
  api-server:
    container_name: api-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
