FROM node:22-slim

# Install Git and other packages using apt-get
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    git \
    bash \
    curl \
    python3 \
    make \
    g++ \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 5000

CMD [ "npm","run","start" ]